@hostname = http://localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json

POST {{hostname}}:{{port}}/urlShorter HTTP/1.1
content-type: {{contentType}}

{
    "url": "https://www.amazon.com"
}

###

GET https://url-shortener-express-dev-mjpt.1.us-1fl0.io/6wacj HTTP/1.1
